// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAgdeKHXIzHPWZvAldl0CkmPEHWWUAVcc',
    appId: '1:191391204611:web:4b55c35b15bbe59836d536',
    messagingSenderId: '191391204611',
    projectId: 'fruitshub-f3682',
    authDomain: 'fruitshub-f3682.firebaseapp.com',
    storageBucket: 'fruitshub-f3682.firebasestorage.app',
    measurementId: 'G-G6D79SDBZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYcFb5ITvayqAMGKcME8LWgJrbYqSD-v4',
    appId: '1:191391204611:android:9e46ee4cd8f1c09e36d536',
    messagingSenderId: '191391204611',
    projectId: 'fruitshub-f3682',
    storageBucket: 'fruitshub-f3682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX79SCFdSAD1w0Cq3Sp-HY1l_b6kCYJ7Y',
    appId: '1:191391204611:ios:ddd7dbb760c112c636d536',
    messagingSenderId: '191391204611',
    projectId: 'fruitshub-f3682',
    storageBucket: 'fruitshub-f3682.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX79SCFdSAD1w0Cq3Sp-HY1l_b6kCYJ7Y',
    appId: '1:191391204611:ios:ddd7dbb760c112c636d536',
    messagingSenderId: '191391204611',
    projectId: 'fruitshub-f3682',
    storageBucket: 'fruitshub-f3682.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAgdeKHXIzHPWZvAldl0CkmPEHWWUAVcc',
    appId: '1:191391204611:web:0c3ef27950cc854836d536',
    messagingSenderId: '191391204611',
    projectId: 'fruitshub-f3682',
    authDomain: 'fruitshub-f3682.firebaseapp.com',
    storageBucket: 'fruitshub-f3682.firebasestorage.app',
    measurementId: 'G-Z7T1HHQLD4',
  );
}
